window.dishes = [
    // Món Nhật
    { name: "Sushi cá hồi", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sashimi tổng hợp", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tempura tôm", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Ramen mì bò", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Udon hải sản", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Okonomiyaki", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Takoyaki", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Yakitori gà nướng", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Miso súp", type: ["Món Nhật"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Onigiri cơm nắm", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Katsu gà chiên", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Donburi bò", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sukiyaki", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Shabu-shabu", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Tonkatsu heo chiên", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gyoza há cảo", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chawanmushi trứng hấp", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tamagoyaki trứng cuộn", type: ["Món Nhật"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Natto đậu lên men", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Soba mì lạnh", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa"] },
    { name: "Zaru soba", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa"] },
    { name: "Kare raisu cà ri", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Yakisoba mì xào", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Oden món hầm", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Unagi lươn nướng", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chirashi sushi", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Teppanyaki bò", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Yakizakana cá nướng", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Anmitsu tráng miệng", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mochi đậu đỏ", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dango bánh gạo", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Taiyaki bánh cá", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Matcha trà xanh", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Hojicha trà rang", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Genmaicha trà gạo", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Edamame đậu nành luộc", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kombucha trà lên men", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Tamago sando bánh mì trứng", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Shio ramen mì muối", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mochigome cơm nếp", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kamameshi cơm nồi đất", type: ["Món Nhật"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Korokke khoai tây chiên", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nikujaga thịt hầm", type: ["Món Nhật"], mealTime: ["ăn tối"] },
    { name: "Tofu chiên", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Yuba đậu phụ mỏng", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Umeboshi mơ muối", type: ["Món Nhật", "đồ khô"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Kimpira gobou rễ ngưu bàng", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hijiki rong biển", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sake rượu gạo", type: ["Món Nhật", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Agedashi tofu", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho Món Nhật (ăn sáng)
    { name: "Cháo gạo Nhật", type: ["Món Nhật"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì kẹp cá mòi", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu đỏ Nhật", type: ["Món Nhật"], mealTime: ["ăn sáng"] },
    { name: "Cơm nắm cá ngừ", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Trứng luộc nước tương", type: ["Món Nhật"], mealTime: ["ăn sáng"] },
    { name: "Salad rong biển", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh gạo nướng", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Cơm chiên miso", type: ["Món Nhật"], mealTime: ["ăn sáng"] },
    { name: "Súp nấm shiitake", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Đậu phụ sốt miso", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Cơm nắm mơ muối", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu hũ kombu", type: ["Món Nhật", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh dày Nhật", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Cá thu kho miso", type: ["Món Nhật"], mealTime: ["ăn sáng"] },
    { name: "Cơm nắm trứng muối", type: ["Món Nhật", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp trứng miso", type: ["Món Nhật"], mealTime: ["ăn sáng"] },

    // Món Ý
    { name: "Pizza Margherita", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Pasta Carbonara", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Lasagna", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Spaghetti Bolognese", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Risotto nấm", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Tiramisu", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Panna Cotta", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bruschetta cà chua", type: ["Món Ý", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Focaccia", type: ["Món Ý"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Gnocchi khoai tây", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Ravioli phô mai", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Pesto pasta", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Minestrone súp rau", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Caprese salad", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Espresso", type: ["Món Ý", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Cappuccino", type: ["Món Ý", "nước uống"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Gelato kem", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cannoli", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Arancini cơm viên", type: ["Món Ý", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Polenta ngô", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Ossobuco thịt hầm", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Frittata trứng", type: ["Món Ý"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Panzanella salad", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa"] },
    { name: "Calzone", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Amaretti bánh quy", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Biscotti", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Zabaglione kem trứng", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn tối"] },
    { name: "Sfogliatelle bánh tầng", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Crostini gan", type: ["Món Ý", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Polpette thịt viên", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tortellini", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cacciatore gà", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Ribollita súp", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Panettone bánh ngọt", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Stracciatella súp trứng", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Limoncello", type: ["Món Ý", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Grissini que bánh mì", type: ["Món Ý", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Pappardelle mì dẹt", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Zuppa Toscana súp", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Saltimbocca thịt bò", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Ciabatta bánh mì", type: ["Món Ý"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Affogato cà phê kem", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Pesto genovese", type: ["Món Ý", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Crostata bánh trái cây", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Farfalle mì nơ", type: ["Món Ý"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Vitello Tonnato thịt bê", type: ["Món Ý"], mealTime: ["ăn tối"] },
    { name: "Torta Caprese bánh socola", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Zeppole bánh rán", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Aperitivo cocktail", type: ["Món Ý", "nước uống"], mealTime: ["ăn tối"] },
    // Thêm món mới cho Món Ý (ăn sáng)
    { name: "Bánh mì ciabatta trứng", type: ["Món Ý"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu Ý", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì focaccia rau củ", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Trứng chiên Ý", type: ["Món Ý"], mealTime: ["ăn sáng"] },
    { name: "Bánh biscotti hạnh nhân", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Súp cà chua Ý", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì nướng phô mai", type: ["Món Ý"], mealTime: ["ăn sáng"] },
    { name: "Salad trái cây Ý", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh cornetto", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Súp polenta", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì ciabatta mứt", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Trứng ốp la phô mai", type: ["Món Ý"], mealTime: ["ăn sáng"] },
    { name: "Bánh croissant Ý", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Súp rau củ Ý", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì nướng cà chua", type: ["Món Ý", "đồ chay"], mealTime: ["ăn sáng"] },

    // Món Hàn
    { name: "Kimchi cải thảo", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Bibimbap cơm trộn", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bulgogi bò nướng", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tteokbokki bánh gạo cay", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Samgyeopsal thịt ba chỉ nướng", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Jajangmyeon mì đen", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Japchae miến xào", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kimchi jjigae súp kimchi", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Soondubu jjigae đậu hũ cay", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kimbap cơm cuộn", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Galbi sườn nướng", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Mandu bánh xếp", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dakgalbi gà xào cay", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Haemul pajeon bánh hải sản", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Soju rượu gạo", type: ["Món Hàn", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Makgeolli rượu đục", type: ["Món Hàn", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Banchan món ăn kèm", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Naengmyeon mì lạnh", type: ["Món Hàn"], mealTime: ["ăn trưa"] },
    { name: "Gyeran jjim trứng hấp", type: ["Món Hàn"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Hotteok bánh pancake ngọt", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bingsu đá bào", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sikhye nước gạo", type: ["Món Hàn", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sujeonggwa trà quế", type: ["Món Hàn", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Gochujang sốt ớt", type: ["Món Hàn", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dakgangjeong gà chiên sốt", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sundae huyết heo", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Tteokguk súp bánh gạo", type: ["Món Hàn"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Yukgaejang súp bò cay", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hobakjuk cháo bí đỏ", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Kongguksu mì đậu nành", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn trưa"] },
    { name: "Jokbal chân giò hầm", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Odeng cá viên", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bossam thịt luộc", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Seolleongtang súp bò", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gamjatang súp khoai tây", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Mul naengmyeon mì nước lạnh", type: ["Món Hàn"], mealTime: ["ăn trưa"] },
    { name: "Dotorimuk thạch hạt dẻ", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Ojingeo bokkeum mực xào", type: ["Món Hàn"], mealTime: ["ăn tối"] },
    { name: "Ganjang gejang cua ngâm", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Yangnyeom gejang cua cay", type: ["Món Hàn"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Baechu kimchi", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Kkakdugi kimchi củ cải", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Yakgwa bánh gừng", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chapssal tteok bánh nếp", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Songpyeon bánh gạo", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dasik bánh quy truyền thống", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Jeon bánh rán", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hwachae nước trái cây", type: ["Món Hàn", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho Món Hàn (ăn sáng)
    { name: "Cháo gạo Hàn", type: ["Món Hàn"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì kimbap trứng", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu hũ Hàn", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Cơm trộn rau củ", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh gạo nướng cay", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp bí đỏ Hàn", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Trứng cuộn Hàn", type: ["Món Hàn"], mealTime: ["ăn sáng"] },
    { name: "Bánh jeon rau củ", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Súp kimchi chay", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Cơm nắm kimchi", type: ["Món Hàn", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu tương", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh nếp Hàn", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Súp rong biển Hàn", type: ["Món Hàn", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Cơm trộn trứng", type: ["Món Hàn"], mealTime: ["ăn sáng"] },

    // Món Việt
    { name: "Phở bò", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Bún bò Huế", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì pate", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh xèo", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gỏi cuốn", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cơm tấm sườn", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bún riêu cua", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả giò", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Canh chua cá lóc", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cuốn", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bò kho", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cao lầu", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mì Quảng", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh bèo", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh bột lọc", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước mắm", type: ["Món Việt", "đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè ba màu", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chưng", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh tét", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Cà phê sữa đá", type: ["Món Việt", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước mía", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bún chả", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hủ tiếu Nam Vang", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh đúc", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai mì", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cơm gà Hải Nam", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bò bía", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả lụa", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Xôi gà", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Cơm chiên dương châu", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh ít trần", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước sâm bổ lượng", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh flan", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gỏi gà xé phay", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cá kho tộ", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh canh cua", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh ướt thịt nướng", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè đậu trắng", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cam", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh da lợn", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mắm chưng", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bún nước lèo", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoái", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chanh dây", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chuối hấp", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh giầy", type: ["Món Việt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Cơm lam", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả cá Lã Vọng", type: ["Món Việt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh tôm Hồ Tây", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước dừa tươi", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho Món Việt (ăn sáng)
    { name: "Bánh mì ốp la", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Xôi đậu xanh", type: ["Món Việt"], mealTime: ["ăn sáng"] },
    { name: "Bánh cuốn chả quế", type: ["Món Việt"], mealTime: ["ăn sáng"] },
    { name: "Cháo gà", type: ["Món Việt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì chả cá", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Xôi ngô", type: ["Món Việt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì trứng ốp", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Cháo lòng", type: ["Món Việt"], mealTime: ["ăn sáng"] },
    { name: "Bánh bao trứng cút", type: ["Món Việt", "đồ ăn vặt"], mealTime: ["ăn sáng"] },

    // Đồ chay
    { name: "Salad rau củ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cơm chiên rau củ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu hũ chiên giòn", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nấm xào sả ớt", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bún xào rau", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Súp bí đỏ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả chay", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gỏi ngó sen", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh bao chay", type: ["đồ chay"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Canh nấm rau củ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu hũ kho nấm", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mì căn xào", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Rau củ luộc", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh xèo chay", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cơm chiên đậu hũ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Súp đậu lăng", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mì Ý chay", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Salad đậu phụ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nấm rơm kho tiêu", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Canh cải ngọt", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Chè đậu đỏ", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa đậu nành", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Rau cải xào tỏi", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cà tím nướng", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bắp rang chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả lụa chay", type: ["đồ chay"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Canh bí đao", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu hũ nhồi nấm", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai lang", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gỏi bắp chuối", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép cà rốt", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Cơm gạo lứt", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mì căn kho", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Rau muống xào", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh đúc chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè khoai tím", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép dưa leo", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Đậu hũ sốt cà", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Canh khoai mỡ", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh bèo chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Salad trái cây", type: ["đồ chay", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nấm bào ngư xào", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chuối chay", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa hạt điều", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Canh rong biển chay", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai môn", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu hũ chiên sả", type: ["đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho đồ chay (ăn sáng)
    { name: "Cháo nấm chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì chay pate", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp khoai lang chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Cơm gạo lứt đậu hũ", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh bao nấm chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Súp bí đỏ chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Xôi đậu xanh chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Salad rau trộn chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh nếp chay", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Súp đậu đỏ chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì nấm chay", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Cơm chiên hạt điều", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Súp rau củ chay", type: ["đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh đúc đậu xanh", type: ["đồ chay", "đồ ăn vặt"], mealTime: ["ăn sáng"] },

    // Đồ ăn vặt
    { name: "Khoai tây chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bắp rang bơ", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh tráng trộn", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt dưa", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh quy bơ", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kem que", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Xúc xích chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì que", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh donut", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Phô mai que", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh gạo", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt điều rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Khoai lang chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cá nướng", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chuối chiên", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt bí rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì bơ tỏi", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh taco", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh ngô chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kẹo dẻo", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh phồng tôm", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mực khô", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh đa nướng", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt óc chó", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh ống lá dứa", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh quế", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh snack", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì chà bông", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Hạt mắc ca", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh xốp", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh bao chiên", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh mì kẹp kem", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chả cá viên chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì trứng", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh khoai chiên", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt dẻ rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì phô mai", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh quy socola", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì nướng muối ớt", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh tráng nướng", type: ["đồ ăn vặt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh su kem", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì chảo", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh đậu xanh", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cốm", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh pía", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh churros", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì pate gan", type: ["đồ ăn vặt"], mealTime: ["ăn sáng", "ăn trưa"] },
    // Thêm món mới cho đồ ăn vặt (ăn sáng)
    { name: "Bánh mì kẹp chả lụa", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh bao nhân trứng", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh quẩy", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh giầy nhân đậu", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì nướng pate", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh bao ngọt", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh rế", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì chả bò", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh khoai môn chiên", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì kẹp rau", type: ["đồ ăn vặt", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì trứng muối", type: ["đồ ăn vặt"], mealTime: ["ăn sáng"] },

    // Trái cây
    { name: "Xoài", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dưa hấu", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cam", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Chuối", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Táo", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Dứa", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bưởi", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Lê", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nho", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dâu tây", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mận", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Ổi", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sầu riêng", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mít", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chôm chôm", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nhãn", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Vải", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Thanh long", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đu đủ", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Măng cụt", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bơ", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Hồng", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dừa", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cherry", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kiwi", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Lựu", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tầm", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Vú sữa", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mơ", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đào", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bòn bon", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Na", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Me", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cóoc", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sapoche", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Khế", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sơ ri", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cà na", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tắc", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dâu da", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trám", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mận hậu", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cà phê trái", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hồng xiêm", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bưởi da xanh", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cam sành", type: ["trái cây"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Chanh dây", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dừa xiêm", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mít tố nữ", type: ["trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Salad xoài", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Dưa hấu cắt lát", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Mận muối", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Ổi gọt sẵn", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Dứa cắt miếng", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Nho trộn sữa chua", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Dâu tây tươi", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Bưởi bóc múi", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Mít thái lát", type: ["trái cây"], mealTime: ["ăn sáng"] },
    { name: "Sầu riêng tách múi", type: ["trái cây"], mealTime: ["ăn sáng"] },

    // Nước uống
    { name: "Trà xanh", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà sữa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước cam ép", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước chanh", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố xoài", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép táo", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sữa tươi", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước dừa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà đào", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép dứa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cà phê đen", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ngọt có ga", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố bơ", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép cà chua", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà hoa nhài", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép dưa hấu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa chua uống", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà ô long", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép ổi", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố dâu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước lọc", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà gừng", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép lựu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố chuối", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà bạc hà", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép cần tây", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sữa hạt óc chó", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép thanh long", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà vải", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố mãng cầu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép bưởi", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà hoa cúc", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép chanh dây", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố dưa gang", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà chanh", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép mận", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa bắp", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép kiwi", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà atiso", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sinh tố sapoche", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép dâu tây", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà sữa trân châu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép nho", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố mít", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà hoa hồng", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép chôm chôm", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố nhãn", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép vải", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà sâm dứa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },

    // Đồ nước
    { name: "Nước mắm chấm", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tương ớt", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tương cà", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm chả giò", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tương đen", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bún chả", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt mayonnaise", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt cà chua", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm gỏi cuốn", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt me", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh xèo", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt phô mai", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bò bía", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt BBQ", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh cuốn", type: ["đồ nước"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Sốt tỏi ớt", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm chả cá", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt mè rang", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm nem chua", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt chua ngọt", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh bèo", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt đậu phộng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm mực nướng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt teriyaki", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh bột lọc", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt wasabi", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm gà nướng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt mù tạt", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm cá chiên", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt hoisin", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bún thịt nướng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt pesto", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm chả lụa", type: ["đồ nước"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Sốt kem", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh tôm", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt cà ri", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh khoái", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt mật ong", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm mì Quảng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt tiêu đen", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm cá kho", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt tương miso", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bún riêu", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt bơ tỏi", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm bánh ướt", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt gừng", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm cao lầu", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt ớt xanh", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chấm hủ tiếu", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sốt kem chanh", type: ["đồ nước"], mealTime: ["ăn trưa", "ăn tối"] },

    // Đồ khô
    { name: "Umeboshi mơ muối", type: ["Món Nhật", "đồ khô"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Hạt dưa", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt điều rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt bí rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mực khô", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt óc chó", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt mắc ca", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt dẻ rang", type: ["đồ ăn vặt", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gochujang sốt ớt", type: ["Món Hàn", "đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cá khô", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Tôm khô", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt dừa", type: ["đồ khô", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt gừng", type: ["đồ khô", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt hướng dương", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu phộng rang", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nho khô", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mơ khô", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chà là khô", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạnh nhân rang", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt hồ trăn", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Thịt bò khô", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Thịt heo khô", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Khô gà lá chanh", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Rong biển sấy", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu nành rang", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt xoài", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt dứa", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt chia khô", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt lanh rang", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt me", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt chuối", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu xanh sấy", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt thông rang", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt táo", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt cam", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Khô mực tẩm gia vị", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Đậu đỏ sấy", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt mãng cầu", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt quinoa sấy", type: ["đồ khô", "đồ chay"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt ổi", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt chanh dây", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hạt macadamia", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mứt dâu tây", type: ["đồ khô", "trái cây"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Khô bò cay", type: ["đồ khô"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho đồ khô (ăn sáng)
    { name: "Hạt dưa muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Đậu phộng muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Hạt hướng dương muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Hạnh nhân muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Hạt hồ trăn muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Nho khô trộn sữa chua", type: ["đồ khô", "trái cây"], mealTime: ["ăn sáng"] },
    { name: "Mơ khô trộn mật ong", type: ["đồ khô", "trái cây"], mealTime: ["ăn sáng"] },
    { name: "Chà là khô nhồi hạt", type: ["đồ khô", "trái cây"], mealTime: ["ăn sáng"] },
    { name: "Hạt chia ngâm sữa", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Hạt lanh trộn yến mạch", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Đậu nành rang muối", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Rong biển sấy muối", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Mứt gừng khô", type: ["đồ khô", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Mứt dừa non", type: ["đồ khô", "bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Hạt thông muối", type: ["đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Đậu xanh rang muối", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Mứt xoài khô", type: ["đồ khô", "trái cây"], mealTime: ["ăn sáng"] },
    { name: "Hạt quinoa trộn sữa", type: ["đồ khô", "đồ chay"], mealTime: ["ăn sáng"] },

    // Bánh ngọt
    { name: "Tiramisu", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Panna Cotta", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Gelato kem", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cannoli", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Amaretti bánh quy", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Biscotti", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Zabaglione kem trứng", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn tối"] },
    { name: "Sfogliatelle bánh tầng", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Panettone bánh ngọt", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Crostata bánh trái cây", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Affogato cà phê kem", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Torta Caprese bánh socola", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Zeppole bánh rán", type: ["Món Ý", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Anmitsu tráng miệng", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Mochi đậu đỏ", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dango bánh gạo", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Taiyaki bánh cá", type: ["Món Nhật", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Hotteok bánh pancake ngọt", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bingsu đá bào", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Yakgwa bánh gừng", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chapssal tteok bánh nếp", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Songpyeon bánh gạo", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Dasik bánh quy truyền thống", type: ["Món Hàn", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè ba màu", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai mì", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh flan", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè đậu trắng", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cam", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh da lợn", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chuối hấp", type: ["Món Việt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh đậu xanh", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh cốm", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh pía", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh churros", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh quy bơ", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Kem que", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh donut", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Bánh chuối chiên", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh ống lá dứa", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh quế", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh xốp", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh mì kẹp kem", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh quy socola", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh su kem", type: ["đồ ăn vặt", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè đậu đỏ", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai lang", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Chè khoai tím", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh chuối chay", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Bánh khoai môn", type: ["đồ chay", "bánh ngọt"], mealTime: ["ăn trưa", "ăn tối"] },
    // Thêm món mới cho bánh ngọt (ăn sáng)
    { name: "Bánh mì ngọt", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh bông lan", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh quy yến mạch", type: ["bánh ngọt", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì sữa", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh bao ngọt chay", type: ["bánh ngọt", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh chà là", type: ["bánh ngọt", "đồ khô"], mealTime: ["ăn sáng"] },
    { name: "Bánh quy hạnh nhân", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì nướng mứt", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh nếp ngọt", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh đậu đỏ", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh chuối nướng", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh cốm ngọt", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh khoai lang nướng", type: ["bánh ngọt", "đồ chay"], mealTime: ["ăn sáng"] },
    { name: "Bánh dừa nướng", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh quy trà xanh", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh mì chuối", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },
    { name: "Bánh nếp đậu xanh", type: ["bánh ngọt"], mealTime: ["ăn sáng"] },

    // Nước uống (giữ nguyên, không cần thêm)
    { name: "Trà xanh", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà sữa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước cam ép", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước chanh", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố xoài", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép táo", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sữa tươi", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước dừa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Trà đào", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép dứa", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Cà phê đen", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ngọt có ga", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố bơ", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước ép cà chua", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà hoa nhài", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép dưa hấu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa chua uống", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà ô long", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép ổi", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố dâu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước lọc", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà gừng", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép lựu", type: ["nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sinh tố chuối", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Trà bạc hà", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép cần tây", type: ["nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Cà phê sữa đá", type: ["Món Việt", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước mía", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước sâm bổ lượng", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước chanh dây", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Nước dừa tươi", type: ["Món Việt", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Matcha trà xanh", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Hojicha trà rang", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Genmaicha trà gạo", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Kombucha trà lên men", type: ["Món Nhật", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sake rượu gạo", type: ["Món Nhật", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Espresso", type: ["Món Ý", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Cappuccino", type: ["Món Ý", "nước uống"], mealTime: ["ăn sáng", "ăn trưa"] },
    { name: "Limoncello", type: ["Món Ý", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Aperitivo cocktail", type: ["Món Ý", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Soju rượu gạo", type: ["Món Hàn", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Makgeolli rượu đục", type: ["Món Hàn", "nước uống"], mealTime: ["ăn tối"] },
    { name: "Sikhye nước gạo", type: ["Món Hàn", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sujeonggwa trà quế", type: ["Món Hàn", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Hwachae nước trái cây", type: ["Món Hàn", "nước uống"], mealTime: ["ăn trưa", "ăn tối"] },
    { name: "Sữa đậu nành", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép cà rốt", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Nước ép dưa leo", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] },
    { name: "Sữa hạt điều", type: ["đồ chay", "nước uống"], mealTime: ["ăn sáng", "ăn trưa", "ăn tối"] }
];